trigger:
- master

jobs:
  - job: Linux
    pool:
      vmImage: Ubuntu-16.04
    strategy:
      matrix:
        Gcc 4.9 x86:
          CONAN_GCC_VERSIONS: 4.9
          CONAN_DOCKER_IMAGE: conanio/gcc49
          CONAN_ARCHS: "x86"
        Gcc 4.9 x86_64:
          CONAN_GCC_VERSIONS: 4.9
          CONAN_DOCKER_IMAGE: conanio/gcc49
          CONAN_ARCHS: "x86_64"
        Gcc 5 x86:
          CONAN_GCC_VERSIONS: 5
          CONAN_DOCKER_IMAGE: conanio/gcc5
          CONAN_ARCHS: "x86"
        Gcc 5 x86_64:
          CONAN_GCC_VERSIONS: 5
          CONAN_DOCKER_IMAGE: conanio/gcc5
          CONAN_ARCHS: "x86_64"
        Gcc 6 x86:
          CONAN_GCC_VERSIONS: 6
          CONAN_DOCKER_IMAGE: conanio/gcc6
          CONAN_ARCHS: "x86"
        Gcc 6 x86_64:
          CONAN_GCC_VERSIONS: 6
          CONAN_DOCKER_IMAGE: conanio/gcc6
          CONAN_ARCHS: "x86_64"
        Gcc 7 x86:
          CONAN_GCC_VERSIONS: 7
          CONAN_DOCKER_IMAGE: conanio/gcc7
          CONAN_ARCHS: "x86"
        Gcc 7 x86_64:
          CONAN_GCC_VERSIONS: 7
          CONAN_DOCKER_IMAGE: conanio/gcc7
          CONAN_ARCHS: "x86_64"
        Gcc 8 x86:
          CONAN_GCC_VERSIONS: 8
          CONAN_DOCKER_IMAGE: conanio/gcc8
          CONAN_ARCHS: "x86"
        Gcc 8 x86_64:
          CONAN_GCC_VERSIONS: 8
          CONAN_DOCKER_IMAGE: conanio/gcc8
          CONAN_ARCHS: "x86_64"
        Clang 3.9 x86:
          CONAN_CLANG_VERSIONS: 3.9
          CONAN_DOCKER_IMAGE: conanio/clang39
          CONAN_ARCHS: "x86"
        Clang 3.9 x86_64:
          CONAN_CLANG_VERSIONS: 3.9
          CONAN_DOCKER_IMAGE: conanio/clang39
          CONAN_ARCHS: "x86_64"
        Clang 4.0 x86:
          CONAN_CLANG_VERSIONS: 4.0
          CONAN_DOCKER_IMAGE: conanio/clang40
          CONAN_ARCHS: "x86"
        Clang 4.0 x86_64:
          CONAN_CLANG_VERSIONS: 4.0
          CONAN_DOCKER_IMAGE: conanio/clang40
          CONAN_ARCHS: "x86_64"
        Clang 5.0 x86:
          CONAN_CLANG_VERSIONS: 5.0
          CONAN_DOCKER_IMAGE: conanio/clang50
          CONAN_ARCHS: "x86"
        Clang 5.0 x86_64:
          CONAN_CLANG_VERSIONS: 5.0
          CONAN_DOCKER_IMAGE: conanio/clang50
          CONAN_ARCHS: "x86_64"
        Clang 6.0 x86:
          CONAN_CLANG_VERSIONS: 6.0
          CONAN_DOCKER_IMAGE: conanio/clang60
          CONAN_ARCHS: "x86"
        Clang 6.0 x86_64:
          CONAN_CLANG_VERSIONS: 6.0
          CONAN_DOCKER_IMAGE: conanio/clang60
          CONAN_ARCHS: "x86_64"
        Clang 7.0 x86:
          CONAN_CLANG_VERSIONS: 7.0
          CONAN_DOCKER_IMAGE: conanio/clang7
          CONAN_ARCHS: "x86"
        Clang 7.0 x86_64:
          CONAN_CLANG_VERSIONS: 7.0
          CONAN_DOCKER_IMAGE: conanio/clang7
          CONAN_ARCHS: "x86_64"
    steps:
      - task: UsePythonVersion@0
        inputs:
         versionSpec: "3.7"
      - script: |
          sudo apt install -y python3-setuptools
          pip3 install --user --upgrade pip
          pip3 install --user --upgrade conan
          pip3 install --user conan_package_tools bincrafters_package_tools
          conan user
          python3 build.py
        displayName: conan create package
  - job: macOS
    pool:
      vmImage: xcode9-macos10.13
    strategy:
      matrix:
        Clang 8.1:
          CONAN_APPLE_CLANG_VERSIONS: 8.1
          XCODE_VERSION: 8.3.3
        Clang 9.0:
          CONAN_APPLE_CLANG_VERSIONS: 9.0
          XCODE_VERSION: 9.2
        Clang 9.1:
          CONAN_APPLE_CLANG_VERSIONS: 9.1
          XCODE_VERSION: 9.4.1
        Clang 10.0:
          CONAN_APPLE_CLANG_VERSIONS: 10.0
          XCODE_VERSION: 10
    steps:
      - script: |
          /bin/bash -c "sudo xcode-select -s /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer"

          brew update || brew update
          brew outdated pyenv || brew upgrade pyenv
          brew install pyenv-virtualenv
          brew install cmake || true
          if which pyenv > /dev/null; then
            eval "$(pyenv init -)"
          fi
          pyenv install 3.7.1
          pyenv virtualenv 3.7.1 conan
          pyenv rehash
          pyenv activate conan

          pip3 install --upgrade pip
          pip3 install --upgrade conan
          pip3 install conan_package_tools bincrafters_package_tools
          conan user

          if which pyenv > /dev/null; then
            eval "$(pyenv init -)"
          fi
          pyenv activate conan
          python3 build.py
        displayName: conan create package
  - job: Windows
    pool:
      vmImage: vs2017-win2016
    strategy:
      matrix:
        VStudio 2017 Release:
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
        VStudio 2017 Debug:
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Debug
    steps:
      - script: |
          set PATH=%PYTHON_HOME%\Scripts;%PATH%
          :: need to add PYTHON_HOME as there is a conflicting chocolatey installed python which is somehow prefered in PATH
          %PYTHON_HOME%/python -m pip install --upgrade pip
          %PYTHON_HOME%/python -m pip install --upgrade conan
          %PYTHON_HOME%/python -m pip install conan_package_tools bincrafters_package_tools
          conan user
          %PYTHON_HOME%/python build.py
        displayName: conan create package
