trigger:
- master

variables:
  reference: "qno/testing"
  current_pkg: "SpeexDSP/1.2rc3/qno/testing"

resources:
  containers:
  - container: cnt_gcc49
    image: conanio/gcc49
  - container: cnt_gcc5
    image: conanio/gcc5
  - container: cnt_gcc6
    image: conanio/gcc6
  - container: cnt_gcc7
    image: conanio/gcc7
  - container: cnt_gcc8
    image: conanio/gcc8
  - container: cnt_clang39
    image: conanio/clang39
  - container: cnt_clang40
    image: conanio/clang40
  - container: cnt_clang50
    image: conanio/clang50
  - container: cnt_clang60
    image: conanio/clang60
  - container: cnt_clang7
    image: conanio/clang7

jobs:
  - job: Linux
    pool:
      vmImage: Ubuntu-16.04
      strategy:
        matrix:
         gcc49:
           containerImage: cnt_gcc49
         gcc5:
           containerImage: cnt_gcc5
         gcc6:
           containerImage: cnt_gcc6
         gcc7:
           containerImage: cnt_gcc7
         gcc8:
           containerImage: cnt_gcc8
         clang39:
           containerImage: cnt_clang39
         clang40:
           containerImage: cnt_clang40
         clang50:
           containerImage: cnt_clang50
         clang60:
           containerImage: cnt_clang60
         clang7:
           containerImage: cnt_clang7
    container: $[ variables['containerResource'] ]
    steps:
      - script: |
          sudo apt install -y python3-setuptools
          sudo pip3 install --upgrade pip
          sudo pip3 install conan
          conan user
        displayName: install conan
      - script: |
          conan create . $(reference)
        displayName: conan create package
      - script: |
          echo "TODO ..."
          conan search
          conan search $(current_pkg)
        displayName: conan publish recipe and package
  - job: macOS
    pool:
      vmImage: xcode9-macos10.13
    steps:
      - script: |
          pip3 install --upgrade pip
          pip3 install conan
          conan user
        displayName: install conan
      - script: |
          conan create . $(reference)
        displayName: conan create package
      - script: |
          echo "TODO ..."
          conan search
          conan search $(current_pkg)
        displayName: conan publish recipe and package
  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - script: |
          :: need to add PYTHON_HOME as there is a conflicting chocolatey installed python which is somehow prefered in PATH
          %PYTHON_HOME%/python -m pip install --upgrade pip
          %PYTHON_HOME%/python -m pip install conan
          conan user
        displayName: install conan
      - script: |
          set PATH=%PYTHON_HOME%\Scripts;%PATH%
          conan create . $(reference)
        displayName: conan create package
      - script: |
          echo "TODO ..."
          conan search
          conan search $(current_pkg)
          SET
        displayName: conan publish recipe and package
