trigger:
- master

variables:
  reference: "qno/testing"
  current_pkg: "SpeexDSP/1.2rc3/qno/testing"

jobs:
  - job: Linux
    pool:
      vmImage: Ubuntu-16.04
    strategy:
      matrix:
        Gcc 4.9 x86:
          CONAN_GCC_VERSIONS: 4.9
          CONAN_DOCKER_IMAGE: conanio/gcc49
          CONAN_ARCHS: "x86"
        Gcc 4.9 x86_64:
          CONAN_GCC_VERSIONS: 4.9
          CONAN_DOCKER_IMAGE: conanio/gcc49
          CONAN_ARCHS: "x86_64"
        Gcc 5 x86:
          CONAN_GCC_VERSIONS: 5
          CONAN_DOCKER_IMAGE: conanio/gcc5
          CONAN_ARCHS: "x86"
        Gcc 5 x86_64:
          CONAN_GCC_VERSIONS: 5
          CONAN_DOCKER_IMAGE: conanio/gcc5
          CONAN_ARCHS: "x86_64"
        Gcc 6 x86:
          CONAN_GCC_VERSIONS: 6
          CONAN_DOCKER_IMAGE: conanio/gcc6
          CONAN_ARCHS: "x86"
        Gcc 6 x86_64:
          CONAN_GCC_VERSIONS: 6
          CONAN_DOCKER_IMAGE: conanio/gcc6
          CONAN_ARCHS: "x86_64"
        Gcc 7 x86:
          CONAN_GCC_VERSIONS: 7
          CONAN_DOCKER_IMAGE: conanio/gcc7
          CONAN_ARCHS: "x86"
        Gcc 7 x86_64:
          CONAN_GCC_VERSIONS: 7
          CONAN_DOCKER_IMAGE: conanio/gcc7
          CONAN_ARCHS: "x86_64"
        Gcc 8 x86:
          CONAN_GCC_VERSIONS: 8
          CONAN_DOCKER_IMAGE: conanio/gcc8
          CONAN_ARCHS: "x86"
        Gcc 8 x86_64:
          CONAN_GCC_VERSIONS: 8
          CONAN_DOCKER_IMAGE: conanio/gcc8
          CONAN_ARCHS: "x86_64"
        Clang 3.9 x86:
          CONAN_CLANG_VERSIONS: 3.9
          CONAN_DOCKER_IMAGE: conanio/clang39
          CONAN_ARCHS: "x86"
        Clang 3.9 x86_64:
          CONAN_CLANG_VERSIONS: 3.9
          CONAN_DOCKER_IMAGE: conanio/clang39
          CONAN_ARCHS: "x86_64"
        Clang 4.0 x86:
          CONAN_CLANG_VERSIONS: 4.0
          CONAN_DOCKER_IMAGE: conanio/clang40
          CONAN_ARCHS: "x86"
        Clang 4.0 x86_64:
          CONAN_CLANG_VERSIONS: 4.0
          CONAN_DOCKER_IMAGE: conanio/clang40
          CONAN_ARCHS: "x86_64"
        Clang 5.0 x86:
          CONAN_CLANG_VERSIONS: 5.0
          CONAN_DOCKER_IMAGE: conanio/clang50
          CONAN_ARCHS: "x86"
        Clang 5.0 x86_64:
          CONAN_CLANG_VERSIONS: 5.0
          CONAN_DOCKER_IMAGE: conanio/clang50
          CONAN_ARCHS: "x86_64"
        Clang 6.0 x86:
          CONAN_CLANG_VERSIONS: 6.0
          CONAN_DOCKER_IMAGE: conanio/clang60
          CONAN_ARCHS: "x86"
        Clang 6.0 x86_64:
          CONAN_CLANG_VERSIONS: 6.0
          CONAN_DOCKER_IMAGE: conanio/clang60
          CONAN_ARCHS: "x86_64"
        Clang 7.0 x86:
          CONAN_CLANG_VERSIONS: 7.0
          CONAN_DOCKER_IMAGE: conanio/clang7
          CONAN_ARCHS: "x86"
        Clang 7.0 x86_64:
          CONAN_CLANG_VERSIONS: 7.0
          CONAN_DOCKER_IMAGE: conanio/clang7
          CONAN_ARCHS: "x86_64"
    steps:
      - script: |
          sudo apt install -y python3-setuptools
          sudo pip3 install --upgrade pip
          sudo pip3 install conan
          sudo pip install  conan_package_tools bincrafters_package_tools
          conan user
        displayName: install conan
      - script: |
          python3 build.py
        env:
          # https://github.com/bincrafters/bincrafters-package-tools
          BINTRAY_REPOSITORY: conan-public
          CONAN_USERNAME: qno
          CONAN_UPLOAD: https://api.bintray.com/conan/qno/conan-public
          CONAN_LOGIN_USERNAME: $(BINTRAY_LOGIN)
          CONAN_PASSWORD: $(BINTRAY_API_KEY)
          CONAN_DOCKER_32_IMAGES: True
        displayName: conan create package
      - script: |
          echo "TODO ..."
          conan search
          conan search $(current_pkg)
        displayName: conan publish recipe and package
  - job: macOS
    pool:
      vmImage: xcode9-macos10.13
    steps:
      - script: |
          pip3 install --upgrade pip
          pip3 install conan
          conan user
        displayName: install conan
      - script: |
          conan create . $(reference)
        displayName: conan create package
      - script: |
          echo "TODO ..."
          conan search
          conan search $(current_pkg)
        displayName: conan publish recipe and package
  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - script: |
          :: need to add PYTHON_HOME as there is a conflicting chocolatey installed python which is somehow prefered in PATH
          %PYTHON_HOME%/python -m pip install --upgrade pip
          %PYTHON_HOME%/python -m pip install conan
          conan user
        displayName: install conan
      - script: |
          set PATH=%PYTHON_HOME%\Scripts;%PATH%
          conan create . $(reference)
        displayName: conan create package
      - script: |
          echo "TODO ..."
          conan search
          conan search $(current_pkg)
          SET
        displayName: conan publish recipe and package
